=== nahiandabie/Personal-Media-Catalog/data/media_catalog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Base type for all media -->
  <xs:complexType name="MediaType" abstract="true">
    <xs:sequence>
      <xs:element name="title" type="xs:string" />
      <xs:element name="year" type="xs:gYear" />
      <xs:element name="genre" type="xs:string" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID" use="required"/>
    <xs:attribute name="type" type="xs:string" use="required"/>
  </xs:complexType>

  <!-- Derived Book type -->
  <xs:complexType name="BookType">
    <xs:complexContent>
      <xs:extension base="MediaType">
        <xs:sequence>
          <xs:element name="author" type="xs:string"/>
          <xs:element name="pages" type="xs:positiveInteger"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <!-- Derived Movie type -->
  <xs:complexType name="MovieType">
    <xs:complexContent>
      <xs:extension base="MediaType">
        <xs:sequence>
          <xs:element name="director" type="xs:string"/>
          <xs:element name="duration" type="xs:string"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <!-- Derived VideoGame type -->
  <xs:complexType name="VideoGameType">
    <xs:complexContent>
      <xs:extension base="MediaType">
        <xs:sequence>
          <xs:element name="platform" type="xs:string"/>
          <xs:element name="developer" type="xs:string"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <!-- Root element -->
  <xs:element name="catalog">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="book" type="BookType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="movie" type="MovieType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="videogame" type="VideoGameType" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== nahiandabie/Personal-Media-Catalog/catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="media_catalog.xsd">
  <book id="b001" type="book">
    <title>Clean Code</title>
    <year>2008</year>
    <genre>Programming</genre>
    <author>Robert C. Martin</author>
    <pages>464</pages>
  </book>

  <movie id="m001" type="movie">
    <title>Inception</title>
    <year>2010</year>
    <genre>Sci-Fi</genre>
    <director>Christopher Nolan</director>
    <duration>148 minutes</duration>
  </movie>

  <videogame id="g001" type="videogame">
    <title>The Witcher 3</title>
    <year>2015</year>
    <genre>RPG</genre>
    <platform>PC</platform>
    <developer>CD Projekt Red</developer>
  </videogame>
</catalog>
